### ISSUE TITLE
Improve font handling

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/thenewdynamic.org#30]
Currently 
- [x] using webpack to load fonts and generate the css (all fine), 
- [x]  also have "pre-load" set in the headers. That's good, 
- [x]  need to make sure we're using the right font files to load only what's necessary, 
- [ ] make sure we're handling our CSS correctly

**Comment by budparr** [comment]
ref 17353c72f632596ffaf266a063a06d564f3fcd9e

**Comment by DirtyF** [comment]
FWIW you could generate an optimized subset of the fonts with glyphanger: https://www.zachleat.com/web/23-minutes/

**Comment by budparr** [comment]
I was thinking about that, but didn't quite understand it, so, I was just horrified by all the fonts I was loading and just ran with a quick win, given here I have the luxury of not supporting older browsers. May revisit soon.

**Comment by budparr** [comment]
So it looks like subsetting can help even if I reduce my stack to WOFF2, if I'm reading that right.

**Comment by DirtyF** [comment]
Yeah you can reduce it to woff2 and woff for modern browsers. I would recommend to check against you own analytics on https://caniuse.com/#feat=woff2 

woff is more widel supported: https://caniuse.com/#feat=woff

**Comment by budparr** [comment]
It's really just IE and older desktop Safari at this point. I just looked on IE and the fonts look fine there—the least of my worries, because I'm using CSS Grid, too (at the moment, without fallbacks, but I'll fix that later).
