### ISSUE TITLE
Design Showcase

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/thenewdynamic.org#34]
Taking the opportunity to re-think the showcase.

- [ ] The landing page should have filtering by tool, similar to the tools directory.

TODO
- [x] Add meta-data to single pages.
- [x] Add previous/next to single pages.
LIST PAGE
- [ ] Consider pagination/scrolling for list page.

IMAGES
- [x] incorporate imgix
- [x] use appropriate sizes 
- [x] make sure we have a way of working locally when the image isn't on imgix
- [x] Optimize ["picture"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) element on list/single pages.
- [x] Add lazyloading for images on list/single pages.
- [x] use a placeholder.

**Comment by budparr** [comment]
forgot to reference this commit [wip] Add showcase single page aa815c5637436289e44c7e1d5a7fb25cb8e8906b

**Comment by budparr** [comment]
Hey, @DirtyF Just checking. This is the code you used to make imgix not load locally, correct?
```
{% if site.image_url == 'http://localhost:3000' %}
    {% assign image = page.image_path | prepend: site.image_url %}
  {% else %}
    {% assign image = page.image_path | prepend: site.image_url | remove: 'uploads/' | append: '?w=900' %}
  {% endif %}
```

**Comment by budparr** [comment]
And I guess, most importantly, I want to make sure that was working to your satisfaction before I replicate that behavior on the new site.

**Comment by DirtyF** [comment]
Whatever you think is best to be able to develop locally, as long as we have all content

**Comment by budparr** [comment]
But what we have now (on the Jekyll site) works for you locally? I just want to make sure it's correct before I port the behavior.

**Comment by budparr** [comment]
Solution to above issue with localhost:

```
{{ if in (print $.Site.BaseURL) "localhost" }}
   ...
{{ else }}
   ... 
{{ end }}
```
https://github.com/thenewdynamic-org/thenewdynamic.org/blob/hugo/layouts/partials/_components/image-picture-element.html#L3
