### ISSUE TITLE
Showcase items styles

### ISSUE THREAD

**Issue by DirtyF** [theNewDynamic/thenewdynamic.org#39]
```
Given I'm on the showcase page
When the browser viewport is < 1048px
And showcase items are not the same height
Then the shadow is not displayed at the bottom of the item
```

![showcase-items-flex](https://user-images.githubusercontent.com/103008/38733704-319da5f8-3f23-11e8-9576-9e2cfe1510a7.png)

Flexbox might be helpful here.

**Comment by budparr** [comment]
this should be fixed now. Thanks!
