### ISSUE TITLE
Submit entry for the showcase

### ISSUE THREAD

**Issue by DirtyF** [theNewDynamic/thenewdynamic.org#48]
- [ ] People can submit entries to be added to the showcase through a public form

* Required info:
  - Name  
  - URL
  - Homepage screenshot (ratio 16/10)
  - Stack (eg. Gatsby, Contentful, Netlify)

- [ ] We can review submissions to the showcase before publishing

**Comment by budparr** [comment]
Fixed in fda9eb5c6913f25ed2fd36a0332300d4d38a3f2a temporarily, until we make a proper form
