### ISSUE TITLE
Submit entry for Find a Developer 

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/thenewdynamic.org#53]
# This information is for developer profiles. If you need help with this, please let us know. If you're leaving an issue for something else, feel free to delete.
---
# your name
title: Régis Philibert
# company name, if applicable
name_organization: 
# your website
link: https://regisphilibert.com
# brief description of the work you do
description: |
I build websites from and occasionally for Montréal 🇨🇦.

I am front end first and foremost, the view is what I love best. That being said being both a Wordpress' old-timer and a Hugo proselyte, if your backend leans on those, I'm here for you.

During slower weeks I enjoy writing about my work on my [blog](https://regisphilibert.com/blog) and learning new things!
# services listed here: https://github.com/thenewdynamic-org/thenewdynamic.org/blob/master/data/services.yaml Feel free to suggest others.   
services: ["Development"]
# Tools you have expertise in. These are tools listed in The New Dynamic. Feel free to suggest others . https://www.thenewdynamic.org/tool/
related_tools: ["algolia", "Disqus", "Forestry", "Grunt", "Gulp", "Hugo", "Netlify", "Webpack", ]
# Showcase items on The New Dynamic. Feel free to suggest your site: https://www.thenewdynamic.org/showcase/
related_showcase: [""]
# where are you located?
location:
  city: Montreal
  country: Canada
---

**Comment by budparr** [comment]
Perfect, thanks!
