### ISSUE TITLE
Add Tool: CloudSh

### ISSUE THREAD

**Issue by candland** [theNewDynamic/thenewdynamic.org#59]
Name: CloudSh Search
Desc: Powerful search for your website with a few lines of JavaScript.

Type: Interaction
License: Commercial
Tags: search

**About**
CloudSh crawls your existing website to build an index for searching. Searching is integrated with a few lines of JavaScript.

**Links**
https://cloudsh.com
https://www.twitter.com/cloudsh
https://github.com/cloudshcom

**Comment by budparr** [comment]
closed with https://github.com/thenewdynamic-org/thenewdynamic.org/commit/dfe1630e8c05381ef4e10378034c4b373ed0979e
